//
//  LYSChartAxisLabelInfo.h
//  LYSChartKitDemo
//
//  Created by HENAN on 2019/9/2.
//  Copyright © 2019 HENAN. All rights reserved.
//

#import "LYSchartInfo.h"

NS_ASSUME_NONNULL_BEGIN

@interface LYSChartAxisLabelInfo : LYSchartInfo
LYSCHARTADDASSIGNPROPERTY(BOOL show);
LYSCHARTADDASSIGNPROPERTY(CGFloat fontSize);
LYSCHARTADDCOPYPROPERTY(NSString *interval);
LYSCHARTADDASSIGNPROPERTY(BOOL inside);
LYSCHARTADDASSIGNPROPERTY(CGFloat rotate);
LYSCHARTADDASSIGNPROPERTY(CGFloat margin);

LYSCHARTADDCOPYPROPERTY(NSString *color);
LYSCHARTADDCOPYPROPERTY(NSString *fontStyle);
LYSCHARTADDCOPYPROPERTY(NSString *fontWeight);

LYSCHARTADDCOPYPROPERTY(NSString *backgroundColor);
LYSCHARTADDCOPYPROPERTY(NSString *borderColor);

LYSCHARTADDASSIGNPROPERTY(CGFloat borderWidth);
LYSCHARTADDASSIGNPROPERTY(CGFloat borderRadius);
@end

NS_ASSUME_NONNULL_END
